import React, { useState } from "react";

function AIChatPanel({ title, context }) {
  const [messages, setMessages] = useState([
    {
      from: "ai",
      text:
        "This panel simulates how the AI assistant will respond once the backend is connected. Ask a question about the regulations or your project to see a placeholder reply.",
    },
  ]);
  const [input, setInput] = useState("");

  const handleSend = (e) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage = { from: "user", text: input.trim() };
    const aiMessage = {
      from: "ai",
      text:
        "In the deployed system this response would be generated by the AI service using your project data and up-to-date regulations. Here it acts as a placeholder for that behaviour.",
    };

    setMessages((prev) => [...prev, userMessage, aiMessage]);
    setInput("");
  };

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 flex flex-col h-[360px] text-xs md:text-sm">
      <div className="flex items-center justify-between mb-2">
        <h3 className="font-semibold text-sm text-slate-900">{title}</h3>
        <span className="text-[10px] text-slate-500">
          Front-end only – AI API to be wired later
        </span>
      </div>

      <p className="text-[11px] md:text-xs text-slate-500 mb-3 leading-relaxed">
        {context}
      </p>

      <div className="flex-1 overflow-y-auto space-y-2 mb-3">
        {messages.map((m, index) => (
          <div
            key={index}
            className={`max-w-[85%] rounded-xl px-3 py-2 leading-relaxed ${
              m.from === "user"
                ? "ml-auto bg-slate-900 text-white"
                : "mr-auto bg-slate-100 text-slate-900 border border-slate-200"
            }`}
          >
            {m.text}
          </div>
        ))}
      </div>

      <form onSubmit={handleSend} className="flex items-center gap-2">
        <input
          className="flex-1 rounded-lg bg-slate-50 border border-slate-300 px-3 py-1.5 text-xs md:text-sm focus:outline-none focus:ring-2 focus:ring-slate-400"
          placeholder="Type a question about the 2025 regulations…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <button
          type="submit"
          className="rounded-md bg-slate-900 px-3 py-1.5 text-xs md:text-sm font-medium text-white hover:bg-slate-800"
        >
          Send
        </button>
      </form>
    </div>
  );
}

export default AIChatPanel;
